### Create report 
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "toyota",
    "model": "corola",
    "year": 1970,
    "mileage": 10000,
    "lng": 0,
    "lat": 0,
    "price": 500000
}