### Signup User - Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test4@test.com",
    "password": "12345"
}

### Signin as esisting user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "12345"
}

### Get the current signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find a particular user with id
GET http://localhost:3000/auth

### find all user
GET http://localhost:3000/auth/3


### find all users with email
GET http://localhost:3000/auth?email=huyvi@pmail.com

### remove a user with id
DELETE http://localhost:3000/auth/52134

### update a user with id
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "huy@gmail.com"
}

### Set session color
GET http://localhost:3000/auth/colors/red

### Get session color
GET http://localhost:3000/auth/colors